development:
  adapter: postgresql
  database: my_database_development
  username: uharston
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  username: uharston
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  username: uharston
  pool: 5
  timeout: 5000